### ISSUE TITLE
Frontmatter camelcase entry

### ISSUE THREAD

**Issue by stebrech** [getkirby/eleventylab#2]
I use eleventyNavigation on some pages which has indented key and order. Kirby overwrites the camelcase written eleventyNavigation and adds a pipe. 

Before saving:
```
eleventyNavigation: 
  key: some key
  order: 3
```

After saving the page in Kirby:
```
eleventynavigation: |
  key: some key
  order: 3
```

Although I currently have this added manually to the markdown files and not integrated into the Kirby Config, CamelCase written objects do not seem to be accepted. I wouldn't know how to manage this indentation either.

**Comment by stebrech** [comment]
With the structure field type it can be configured in Kirby, but still the issue with camelcase and the pipe. Additionally it adds a hyphen:

```
    fields:
      eleventyNavigation:
        label: Link in Hauptmenü
        type: structure
        fields:
          key:
            label: Linktext
            type: text
          order:
            label: Nr. Reihenfolge
            type: number
```

Result:

```
eleventynavigation: |
  -
  key: some key
  order: 9
```
